---
title: "NMDS Workshop1"
author: "Ben Elam"
date: "February 1, 2016"
output: html_document
---

## This Workshop
Goals:

- Provide new users with an idea of how R might be of use to them.
- Make sure that all workshop attendees (new and prior) have a baseline background that can be built upon in future workshops.

Visit [github.com/nmsdataskills/r_basics](https://github.com/nmsdataskills/) to find the latest version of this guide.
You can download the RMarkdown (.Rmd) file to play with in RStudio,
read or download the HTML version of the guide,
or just download a simplified R (.r) script with the code.
You'll also want the data (TODO) to follow along throughout the workshop.

This workshop is not:

- A general primer on programming
- An introduction to statistics or even to statistical programming

See Resources (at bottom) for links to various things we recommend reading or watching.

## North Mississippi Data Skills
We provide accessible training in professional, open-source data workflows and best practices to researchers from various backgrounds.

Our workshops are designed with students with research projects in mind.
We assume that your program of study involves some statistical preparation relevant to your research.
From experience, we also assume that your instructor had to cover a lot statistics,
and only had so much time to cover professional tools.
That's where we hope to be of assistance!

Where
- Hang out with us at [nmsdataskills.slack.com](http://nmsdataskills.slack.com)!
- Access our content at [github.com/nmsdataskills](http://github.com/nmsdataskills). We're happy to have contributions.

## Thanks!
We'd like to thank the MSU Mitchell Memorial Library and the MSU Instructional Media Center
for providing us with this meeting space.

## Loading Data
### The `setwd` Command
### Filepaths
Windows vs *nix

On any platform, R adheres to the Unix format of delimiting directories in a pathname with forward slashes (/).

## Data At A Glance
### Printing A Dataframe
### The `summary` Command
### Visualization With The `plot` Command
```{r, echo=FALSE}
plot(cars)
```

## Basic Data Manipulation and Cleaning
### Understanding Boolean Expressions

### Subset
Syntax

Example selections

Summarize again

Plot again

## Generating Random Data
Don't have your data yet? Not a problem!

### Random 

Choosing reasonable bounds to simulate future data

Remember: fake data is (usually) not a substitute for real data!
The assumption that the distribution or "shape" of your data is remotely similar
to that of the random data generated by the script is unjustified.
After all, that's why you're investigating - to determine if there's a pattern in the data or if it's just noise.

The benefits we're getting here are computational:

- You can write code prior to receiving your data, which might save you time.
- You think about the possible values your observations could take on. What does it mean for an observation to be zero valued? Negative?
- By designing in advance, you're restraining yourself from designing your analysis to suit your data.

## Resources
You can learn about installing R at cran (TODO)

RStudio makes some great documentation: (TODO)

- RStudio cheat sheet
- ggplot cheat sheet
- RMarkdown cheat sheet

I'm a big fan of the Learn X in Y Minutes project, which has [an entry on R](https://learnxinyminutes.com/docs/r/).